public Class TestMerge1
{
public Account createAccount(String name)  //method to create account
{
Account a001922= new Account();
Account a0019223= new Account();// changed
Account a0019221111= new Account();//changed
Account a0019224444= new Account();//changed
// i am changed
a001922.Name = name;//changed
a0019223.Name = name;//changed
a001922.Name = name;//changed
a001922.Name = name;//changed
return a001922;
//test na37
}
}