public Class UatTesst
{
public Account createAccount(String name)  //method to create account
{
Account a001922= new Account();
Account uatTest= new Account();
Account a001922222222222222= new Account();
Account a0019229999999999= new Account();
Account a0019222222555533333333333333333333= new Account();
Account a0019222222555533333333333333555= new Account();
Account a001922977777799= new Account();
Account a0019223= new Account();// changed
Account a0019221111= new Account();//changed
// i am changed
a001922.Name = name;//changed
a0019223.Name = name;//changed
uatTest.Name = name;//uatchanged
return a001922;
//test na37
}
}